# set -ga terminal-overrides ",screen-256color*:Tc"
# set-option -g default-terminal "screen-256color"

set -g default-terminal 'tmux-256color'
# undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# support colors for undercurl
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -s escape-time 0

unbind C-b
set-option -g prefix C-a

set -g status-style 'bg=#333333 fg=#5eacd3'

bind-key -n C-f run-shell "tmux neww tmux-sessionizer"
bind-key l switch-client -l
